INSERT  INTO AUTHOR (AUTHOR_ID ,AUTHOR_NAME ) VALUES (1, 'Фёдор Достоевский');
INSERT INTO GENRE (GENRE_ID ,GENRE_NAME ) VALUES (1,'Художественная проза');
INSERT INTO BOOK (BOOK_ID ,BOOK_NAME,AUTHOR_ID ,GENRE_ID ) VALUES (1,'Идиот','1','1');
INSERT INTO BOOK (BOOK_ID ,BOOK_NAME,AUTHOR_ID ,GENRE_ID ) VALUES (2,'Бесы','1','1');